### ISSUE TITLE
Push to Maven Central

### ISSUE THREAD

**Issue by bilalaslam** [awslabs/aws-dynamodb-encryption-java#1]
Are you planning on releasing to Maven Central?

**Comment by hansonchar** [comment]
The snapshot jar is now available at Maven Central:

  https://oss.sonatype.org/content/repositories/snapshots/com/amazonaws/aws-dynamodb-encryption-java/0.0.3-SNAPSHOT/

You can add the dependency to your maven pom.xml:

```
         <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-dynamodb-encryption-java</artifactId>
            <version>0.0.3-SNAPSHOT</version>
        </dependency>
```

**Comment by hansonchar** [comment]
You can also download it directly from github:

  https://github.com/awslabs/aws-dynamodb-encryption-java/releases/tag/0.0.3-SNAPSHOT

**Comment by bilalaslam** [comment]
Thank you @hansonchar !
