### ISSUE TITLE
0.0.5-SNAPSHOT not in Maven repository

### ISSUE THREAD

**Issue by jbalbien** [awslabs/aws-dynamodb-encryption-java#14]
0.0.5-SNAPSHOT cannot be found in https://oss.sonatype.org/content/repositories/snapshots/com/amazonaws/aws-dynamodb-encryption-java/

**Comment by SalusaSecondus** [comment]
@jbalbien sorry for the delay on this. I don't (personally) have access to publish, so I'll find someone who does.

**Comment by rogernort** [comment]
Any updates on this @SalusaSecondus ? We'd like to use SNAPSHOT 0.0.5 in our new project but it's not simple currently to include it in our project which uses Gradle as the Maven repository listed latest version still seems to be 0.0.3-SNAPSHOT?

**Comment by SalusaSecondus** [comment]
I just repoked this. The delay here was my fault as we got side-tracked in a discussion of patches related to handling document types and lost track of this "Yeah, that's good, but let's get this version out there."

Sorry about that.

**Comment by SalusaSecondus** [comment]
I apologize for the very long delay on this. I have gotten the credentials so I can manage the publishing process myself.  It's up there.
