### ISSUE TITLE
aws-dynamodb-encryption for node js

### ISSUE THREAD

**Issue by sathiya-mit** [awslabs/aws-dynamodb-encryption-java#18]
Do we have aws-dynamodb-encryption for node js ?

**Comment by fulghum** [comment]
Nope, we don't have an implementation for Node JS yet.  If you'd like to request this from the AWS SDK for Node.JS team, you can open an issue with them here:
https://github.com/aws/aws-sdk-js/issues

**Comment by aneilbaboo** [comment]
There's an issue tracking it here: https://github.com/aws/aws-sdk-js/issues/1164

@fulghum - Any update on this?

**Comment by mattsb42-aws** [comment]
@aneilbaboo We don't have one planned at this time, but we're always interested to see customer demand for other languages.

**Comment by aneilbaboo** [comment]
Thanks, @mattsb42-aws - what would you need to see to get this on the roadmap?

FWIW, we will probably migrate away from Dynamo if we can't figure out a way to solve this in Node.js.

**Comment by mattsb42-aws** [comment]
@aneilbaboo Visible customer requests like this and aws/aws-sdk-js#1164 help (thanks for linking that one; I wasn't actually aware of that issue). That helps us in determining customer demand, which helps us prioritize efforts.

Unfortunately, even if we were to commit to building the DDB encryption client in Node right now (which, just for the pedantic record, I can't do here), it would be a while until we had something that you could use.

> FWIW, we will probably migrate away from Dynamo if we can't figure out a way to solve this in Node.js.

That's definitely a good data point. Have you reached out to AWS customer support about this? If you're willing to do that, it would provide a much more tangible data point for us to use.

**Comment by sevees** [comment]
+1
