### ISSUE TITLE
Production release in Maven?

### ISSUE THREAD

**Issue by jbalbien** [awslabs/aws-dynamodb-encryption-java#19]
Has the production release been pushed to Maven? I've been unable to pull it down.

Thanks!

**Comment by SalusaSecondus** [comment]
I see the problem and will get it published today. Sorry about that.

**Comment by SalusaSecondus** [comment]
It looks to be fixed. Please re-open this if I'm wrong.

**Comment by jbalbien** [comment]
I got it working but had to add this repository URL: https://oss.sonatype.org/content/repositories/comamazonaws-1992/com/amazonaws/aws-dynamodb-encryption-java/

Should it be published in https://oss.sonatype.org/content/repositories/releases/com/amazonaws/ instead?

**Comment by SalusaSecondus** [comment]
Now we're definitely outside of my area of expertise. I'll point someone to this who manages much more of our public github face and knows this better.

**Comment by manixsh** [comment]
Hi

You have also published another sdk - https://github.com/awslabs/aws-encryption-sdk-java, which is a generic encryption sdk, and is the latest one. Can you please suggest which one should i use, i have a requirement to encrypt maps in DynamoDB. 

Thanks
Manish

**Comment by SalusaSecondus** [comment]
@manixsh This library (aws-dynamodb-encryption-java) is intended to make encryption with DynamoDB easy and safe. The other library (aws-encryption-sdk-java) is intended to make encryption in general easy and safe.

So, if you are trying to store encrypted data in DynamoDB, definitely use this library.

**Comment by mejran** [comment]
Hi,
Has this been resolved yet, I'm unable to find any public repository where this package is present. https://oss.sonatype.org/content/repositories/comamazonaws-1992/com/amazonaws/aws-dynamodb-encryption-java/ no longer works.

Thanks,
Marcin

**Comment by SalusaSecondus** [comment]
@shorea Mind looking at this?

**Comment by shorea** [comment]
Yep, on it.

**Comment by shorea** [comment]
Can you try again? It may not show up in the browser for a while but you should be able to reference it in your pom.

**Comment by jbalbien** [comment]
Works now, thanks!

**Comment by SalusaSecondus** [comment]
@shorea also helped me to find and the stupid mistake in my release script so this problem shouldn't recur.
