### ISSUE TITLE
Scan query on encrypted column values not working. 

### ISSUE THREAD

**Issue by vmasule** [awslabs/aws-dynamodb-encryption-java#21]
I am using this library for Client side encryption for some of the columns in table.
When I query(DynamoDBScanExpression) on encrypted columns it returning me empty result but If I query on non encrypted columns it returns expected result.

Is this the limitation of the library? Or I am doing something wrong.

**Comment by SalusaSecondus** [comment]
This is a known limitation of the library. Querying (or scanning) on encrypted data isn't supported.

**Comment by vmasule** [comment]
In addition to above query.
I noticed that scanning all records works but in that case if the @DoNotTouch attributes are modified then scanning all records throws bad signature.

Is this also limitation or I am doing something wrong.
Please suggest if I want to update record where some columns are encrypted but some not and I want to retrieve all records.
How I can achieve that?

**Comment by SalusaSecondus** [comment]
Modifying `@DoNotTouch` attributes is safe. However you need to ensure that you really are only modifying just the  `@DoNotTouch`  and that you are always retrieving entire records.
