### ISSUE TITLE
MostRecentProvider- keystore Version Increment

### ISSUE THREAD

**Issue by shay-sundaysky** [awslabs/aws-dynamodb-encryption-java#24]
Hi,
When using MostRecentProvider, when does the materialname version change? Is it always 0?
When dubugging the code, i wasn't able to produce a scenario where the material name version is incremented. What am I doing wrong?

**Comment by SalusaSecondus** [comment]
Current versions do not automatically create new versions. Please take a look at [ProviderStore.newProvider(String)](https://github.com/awslabs/aws-dynamodb-encryption-java/blob/master/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/providers/store/ProviderStore.java#L49-L58)
