### ISSUE TITLE
Adding some notion of DynamoDB key to the KMS encryption context

### ISSUE THREAD

**Issue by copumpkin** [awslabs/aws-dynamodb-encryption-java#28]
I was poking around the `DirectKmsMaterialProvider` and although I had assumed that the table and key (in the DynamoDB sense) ended up in the KMS encryption context somehow, it doesn't appear to. Would that be possible? Are there downsides to adding it? It would make KMS logs much more useful, since we could tell from KMS logs which table entries were being decrypted by whom.

**Comment by SalusaSecondus** [comment]
The table-name, hash, and range keys are included in the KMS EncryptionContext.

* [Table Name](https://github.com/awslabs/aws-dynamodb-encryption-java/blob/master/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/providers/DirectKmsMaterialProvider.java#L263)
* [Hash Key](https://github.com/awslabs/aws-dynamodb-encryption-java/blob/master/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/providers/DirectKmsMaterialProvider.java#L237)
* [Range Key](https://github.com/awslabs/aws-dynamodb-encryption-java/blob/master/src/main/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/providers/DirectKmsMaterialProvider.java#L250)
