### ISSUE TITLE
Maven Artifact Not Found

### ISSUE THREAD

**Issue by lyfbitsadmin** [awslabs/aws-dynamodb-encryption-java#4]
Getting this after adding dependency as specified.

"The POM for com.amazonaws:aws-dynamodb-encryption-java:jar:0.0.3-SNAPSHOT is missing, no dependency information available"

Are you sure you uploaded to Maven central repo?

A search by group and artifiact at search.maven.org yields nothing.

**Comment by hansonchar** [comment]
I just checked and can download the jar from:

  https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=com.amazonaws&a=aws-dynamodb-encryption-java&v=0.0.3-SNAPSHOT&e=jar

It's a pre-release, so not sure if that could be related.

**Comment by hansonchar** [comment]
I've updated the README.md on the main page to include this info:

  https://github.com/awslabs/aws-dynamodb-encryption-java

Thanks for asking!

**Comment by lyfbitsadmin** [comment]
Thank you! Yes, the repository you are using is different. Maven central repo: search.maven.org has no entry for this artifact.
