### ISSUE TITLE
Create a stable release

### ISSUE THREAD

**Issue by GuiSim** [awslabs/aws-dynamodb-encryption-java#5]
We've been using aws-dynamodb-encryption in production for a while now and we'd like to know what's stopping you from releasing a non-snapshot release?

Thanks!

**Comment by shorea** [comment]
Hey sorry for the delay in response here. We discussed internally and agree that it's ready for an official release. I have added a task in our backlog to migrate it out of awslabs and start publishing a non-snapshot release. I'll leave this issue open to track the progress of the effort.

**Comment by binaryblake** [comment]
I second this request - any idea when it will become available?

**Comment by kiran246** [comment]
Hey, any updates on when you are planning to do an official release.

**Comment by SalusaSecondus** [comment]
Not quite yet. I think that we /just/ took care of the last thing on my "must be fixed" list. I'll need to check.

**Comment by pnathan** [comment]
How's this looking? I notice this has revved from 0.7 to 0.9 in the past month or two.

**Comment by SalusaSecondus** [comment]
Sorry. I had a family emergency just as I pushed 0.9.  We're ready to go, I'm just trying to navigate some internal processes.  There is lots of pressure to move this up to an official release and we do want to. It's just process now.

I'm really sorry that it's taking so long.

**Comment by pnathan** [comment]
@SalusaSecondus Dang, sorry to hear that. I was able to frobulate my internal build to use the snapshot, so it's not a crisis on my end. 

(FYI, Leiningen, the Clojure build tool, really hates snapshots).

**Comment by SalusaSecondus** [comment]
Done! See release 1.11.0
