### ISSUE TITLE
Throttling exception when using the DirectKmsMaterialProvider

### ISSUE THREAD

**Issue by jrochette** [awslabs/aws-dynamodb-encryption-java#6]
Hi,

I am using to DirectKmsMaterialProvider and I sometimes get the following exception when my application has high traffic.

`java.util.concurrent.ExecutionException: com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMappingException: com.amazonaws.AmazonServiceException: You have exceeded the rate at which you may call KMS. Reduce the frequency of your calls. (Service: AWSKMS; Status Code: 400; Error Code: ThrottlingException; Request ID: 4d15a2da-441a-11e5-8a71-8d9f87588b5d)`

I know I can ask AWS support to increase the KMS request limit on my account, but I think this is not a viable long term solution.

Is there anything that can be done to reduce the number of calls to KMS ? By batching the decrypt request maybe ?

Thank you,
Jonathan

**Comment by fulghum** [comment]
Hey Jonathan, our suggestion would be to open a case with support to talk about your use case and how much TPS you need, to try and get your KMS limit increased.
https://console.aws.amazon.com/support/home?region=us-east-1#/

Do you have any more details on why this isn't a good long term solution for you?  Are you at a low load now and expecting a lot more?

**Comment by jrochette** [comment]
Hi, I opened a support case as you suggested. 

We are indeed expecting the load to increase over the next weeks/months. I fear that we will hit the increased TPS limit with the increased load on our application and will have to open a new support case to increase the TPS limit again (and so on if the load increase even more).

I am looking for a way to reduce the number of request to dynamoDB in my app (and thus reducing the number of request to KMS). I was wondering if there was any setting or feature in KMS that would save me the trouble.

**Comment by SalusaSecondus** [comment]
There is nothing in KMS which will help here, but it is on my personal backlog to add a caching layer into the encryption client which will solve this problem as well.

(rough outline of solution follows)
Create a meta-provider which takes in a DDB Table and another provider and is used to create a key hierarchy. This way you can still chain all of your keys up to the ultimate provider (KMS in this case) while only needing to access KMS when using or creating a new key.

**Comment by SalusaSecondus** [comment]
Just a quick update, I'm actively working on a caching/indirection layer which should solve your throttling problems with KMS. I don't expect anything this week, but I might have it out next week. No promises though.

**Comment by SalusaSecondus** [comment]
I've implemented a way to build key hierarchies with caching. Though I hope to improve it later, it should be good enough for production use now.

7752c756db31049733490d69656a8efc7fc8a1d0

Please let me know if this works (or has any problems).

**Comment by SalusaSecondus** [comment]
As always, please grab from the tip. There was actually a minor typo in that commit. (Non-security impacting, just a theoretical performance issue in the cache.)

Patched ddf0484f3fb9310d7419f4222a739193e20bb188

**Comment by pbhadauria** [comment]
@SalusaSecondus My org is also hitting throttling limit for KMS. I am not clear about how to use your MostRecentProvider for caching? Can you shed some more light?

**Comment by SalusaSecondus** [comment]
@pbhadauria I really need to draft better docs and an example for that. Essentially, you'd use the MetaStore to manage a DynamoDB table full of (encrypted) keys. These keys would be protected using the DirectKmsMaterialProvider. You'd then protect your actual data using a MostRecentProvider backed by the MetaStore. You'll want to create new versions of data keys in the MetaStore semi-regularly to ensure that you don't encrypt more than 2^32 records with a single key in the MetaStore. (I recommend not passing about 2^30.)

I'll add example code to my long list of things I need to write.

**Comment by pbhadauria** [comment]
@SalusaSecondus thanks for the response. I get it now. One other problem is that the maven repo doesn't contain the most recent artifact, hence the MostRecentProvider is not there. As an alternative, I tried to build this repo itself but it fails with a dependency on dynamodb/mock.

ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project aws-dynamodb-encryption-java: Compilation failure: Compilation failure:
[ERROR] /Users/pbhadauria/tools/aws-dynamodb-encryption-java/src/test/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/providers/store/MetaStoreTests.java:[30,44] package com.amazonaws.services.dynamodb.mock does not exist
[ERROR] /Users/pbhadauria/tools/aws-dynamodb-encryption-java/src/test/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/providers/MostRecentProviderTests.java:[33,44] package com.amazonaws.services.dynamodb.mock does not exist
[ERROR] /Users/pbhadauria/tools/aws-dynamodb-encryption-java/src/test/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/providers/store/MetaStoreTests.java:[59,34] cannot find symbol
[ERROR] symbol:   class AmazonDynamoDBMock
[ERROR] location: class com.amazonaws.services.dynamodbv2.datamodeling.encryption.providers.store.MetaStoreTests
[ERROR] /Users/pbhadauria/tools/aws-dynamodb-encryption-java/src/test/java/com/amazonaws/services/dynamodbv2/datamodeling/encryption/providers/MostRecentProviderTests.java:[64,33] cannot find symbol
[ERROR] symbol:   class AmazonDynamoDBMock
[ERROR] location: class com.amazonaws.services.dynamodbv2.datamodeling.encryption.providers.MostRecentProviderTests

Not sure if I am missing anything.

**Comment by SalusaSecondus** [comment]
@pbhadauria You're correct on both counts and I need to bug some people to fix both of those. I'd recommend (for now) just not building the tests.

**Comment by pbhadauria** [comment]
Cool! Thanks for help.

**Comment by SalusaSecondus** [comment]
@pbhadauria I think that I've fixed all these issues in the newest release. I'll admit that I'm still learning the ins and outs of GitHub and Maven. (I spend most of my time in other systems.)

https://github.com/awslabs/aws-dynamodb-encryption-java/releases/tag/0.0.5-SNAPSHOT

If there are any problems with this, please let me know.

**Comment by pbhadauria** [comment]
@SalusaSecondus  With new changes, mvn is happy. Thanks for quick help.

Your MostRecentProvider worked like a charm. I am bumping up material version in meta store after a given interval and that has, in turn, provided a welcome bit of variability to encryption as well.
